#ifndef GLASGOW_CONSTRAINT_SOLVER_GUARD_GCS_CONSTRAINTS_GLOBAL_CARDINALITY_HH
#define GLASGOW_CONSTRAINT_SOLVER_GUARD_GCS_CONSTRAINTS_GLOBAL_CARDINALITY_HH

#include <gcs/constraints/global_cardinality/bounds_global_cardinality.hh>
#include <gcs/constraints/global_cardinality/global_cardinality.hh>

#endif
