#ifndef GLASGOW_CONSTRAINT_SOLVER_GUARD_GCS_PATH_HH
#define GLASGOW_CONSTRAINT_SOLVER_GUARD_GCS_PATH_HH

#include <gcs/constraints/path/path.hh>

#endif // GLASGOW_CONSTRAINT_SOLVER_GUARD_GCS_PATH_HH
