#ifndef GLASGOW_CONSTRAINT_SOLVER_GUARD_GCS_SUBGRAPH_HH
#define GLASGOW_CONSTRAINT_SOLVER_GUARD_GCS_SUBGRAPH_HH

#include <gcs/constraints/subgraph/subgraph.hh>

#endif // GLASGOW_CONSTRAINT_SOLVER_GUARD_GCS_SUBGRAPH_HH
