#ifndef GLASGOW_CONSTRAINT_SOLVER_GUARD_GCS_TREE_HH
#define GLASGOW_CONSTRAINT_SOLVER_GUARD_GCS_TREE_HH

#include <gcs/constraints/tree/tree.hh>

#endif // GLASGOW_CONSTRAINT_SOLVER_GUARD_GCS_TREE_HH
