name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, macos-15, macos-26 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Fetch VeriPB
      run: git -c core.hooksPath=/dev/null clone --depth 1 https://gitlab.com/MIAOresearch/software/VeriPB.git

    - name: Install VeriPB using cargo
      run: cargo install --path ./VeriPB

    - name: Install MiniZinc using brew
      run: brew install minizincide
      if: startsWith(matrix.os, 'macos')

    - name: Configure CMake
      run: cmake --preset release -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --parallel $(nproc 2>/dev/null || sysctl -n hw.logicalcpu)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -j $(nproc 2>/dev/null || sysctl -n hw.logicalcpu) --output-on-failure --rerun-failed

  sanitize:
    name: Sanitize (ubuntu-24.04)
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Fetch VeriPB
      run: git -c core.hooksPath=/dev/null clone --depth 1 https://gitlab.com/MIAOresearch/software/VeriPB.git

    - name: Install VeriPB using cargo
      run: cargo install --path ./VeriPB

    - name: Configure CMake (Sanitize)
      run: cmake --preset sanitize -B ${{github.workspace}}/build-sanitize

    - name: Build (Sanitize)
      run: cmake --build ${{github.workspace}}/build-sanitize --parallel $(nproc 2>/dev/null || sysctl -n hw.logicalcpu)

    - name: Test (Sanitize)
      working-directory: ${{github.workspace}}/build-sanitize
      run: ctest -j $(nproc 2>/dev/null || sysctl -n hw.logicalcpu) --output-on-failure --rerun-failed
      env:
        ASAN_OPTIONS: detect_leaks=1:halt_on_error=1
        UBSAN_OPTIONS: halt_on_error=1:print_stacktrace=1
